### ISSUE TITLE
Check Authorization header case-insensitive.

### ISSUE THREAD

**Issue by Zegnat** [dg01d/nanopub#1]
As [noted on the documentation page for `getallheaders`](https://secure.php.net/manual/en/function.getallheaders.php#52029):

> Beware that RFC2616 (HTTP/1.1) defines header fields as case-insensitive entities. Therefore, array keys of getallheaders() should be converted first to lower- or uppercase and processed such.

nanopub [currently requires](https://github.com/dg01d/nanopub/blob/8124f44fcc10d4a6a23355949d12b149cd96d2e7/nanopub.php#L81) a case-sensitive `Authorization`. This means it does not work with [Omnibear](https://omnibear.com/) which in my testing sends a lowercased `authorization` header instead.

nanopub should be accepting all possible cases of the received header.

**Comment by dg01d** [comment]
I'll happily accept a PR to cope with these requirements, Zegnat 👍

**Comment by Zegnat** [comment]
If the right array is being lowercased (see [my comment](https://github.com/dg01d/nanopub/commit/85d31a18262a7fb0931b687eac44b4ec57cb37b9#commitcomment-25255480)) then I get it to work with shpub and Omnibear. With your current change it breaks in shpub and only works in Omnibear because you are lowercasing the wrong array.

**Comment by dg01d** [comment]
I changed the entire system to a flat array as per your comment. Please let me know if this makes it work.

**Comment by Zegnat** [comment]
Current master branch works for me in both Omnibear and shpub. Going to close this.

Nicely done!
