### ISSUE TITLE
Plugin mechanism

### ISSUE THREAD

**Issue by skpy** [dg01d/nanopub#10]
I have a need for my micropub endpoint to occasionally do something more than just create a YAML file.  I might want to add elements to a JSON data structure for use with Hugo data-driven templates, for example.  It would be swell if Nanopub could support invoking additional scripts by way of a plugin mechanism.

**Comment by dg01d** [comment]
That's not something I'm going to be doing with this script. Its already quite a bit larger than I had hoped (and as its ill-chosen moniker would suggest!) I just wanted to make something that would comply with the [Micropub Specification](https://www.w3.org/TR/micropub/), and I've added some functions which are popular in the Indieweb community.

If you'd like to make a plugin system yourself, I'd be happy to look at any PR you might offer, the current weather-optional stuff is probably a decent indicator of how it might be obtained.

**Comment by skpy** [comment]
I'll see what I can do.  Arguably, each of Twitter, Mastodon, and weather could be plugins, because they're not core parts of the micropub transaction; or at least not every user will use each of them.
