### ISSUE TITLE
Installation clarification

### ISSUE THREAD

**Issue by kaushalmodi** [dg01d/nanopub#13]
Hello,

In the Installation instructions, it says:

> Since the 1.2 release, nanopub requires the use of Composer. Getting it to do all the things I wanted it to do was getting way beyond my skill level.

I have 0 experience with PHP, and don't plan to tinker with the code. 

So I assume that installing Composer is not a requirement?

Can you please list the installation steps just to get the endpoint running for someone with no PHP experience like myself?

**Comment by dg01d** [comment]
I shall be attending to this issue RSN. I see what you're saying about composer, and I'll be coming up with a workaround also.

**Comment by dg01d** [comment]
Closing this now. Instructions for installation _via_ composer & by use of zip files updated.

**Comment by kaushalmodi** [comment]
Thank you. I am in the process of committing these files to my site. Though, I have one basic question.. when and where will the script is creating the content files.. I mean.. once hugo is done generating the site, how would the nanopub generated content files matter. Wondering if this will work for my case where the site is hosted via Netlify. In any case, I'll still try this out.

Also, the vendor/ dir is huge, I guess I can start by not committing only the test files from there, right?
