### ISSUE TITLE
storeFolder and trashFolder are still hardcoded (in the source of the 1.5.1 zip)

### ISSUE THREAD

**Issue by metbril** [dg01d/nanopub#18]
The installation documentation 

https://github.com/dg01d/nanopub/blob/master/INSTALLATION.md

mentions settings for 

- storageFolder 
- trashFolder

since commit:

https://github.com/dg01d/nanopub/commit/7699a88baab32cfdb8dbbe429b105ada01524281

The storage locations however are still hardcoded in the source.

**Comment by metbril** [comment]
i am working on a pr

**Update**: I downloaded the latest ZIP from the releases page. That does not yet use the storageFolder. The master branch does. You should create a new release for download.

**Comment by dg01d** [comment]
New release and .zip provide the current master in zip composer-installed form.

Closing this as a result.
