### ISSUE TITLE
Add support for YAML front matter format

### ISSUE THREAD

**Issue by paulrobertlloyd** [dg01d/nanopub#3]
Hello! This looks like a fantastic project – although sadly just one of only a few options available for anyone wanting to implement MicroPub and publish to a statically-generated site.

How difficult/possible would it be to add support for documents that use YAML for their front matter data, rather than JSON? I know Hugo documents can use YAML as well as JSON (and TOML), but perhaps more to the point, Jekyll documents only use YAML. Adding this format would increase the number of static generators Nanopub is able to support. (Looking at the code, I suspect being able to configure where documents are saved would be needed to fully support Jekyll, but I can add that as a separate issue, if that’s the case.)

Any plans to support YAML? If not, pointers as to where and what to edit would be most helpful.

Thanks,

Paul

**Comment by dg01d** [comment]
I hadn't realised that Jekyll was YAML only.

Bizarrely, I've been working on a different project for myself which _might_ help out here. I'll have a look at what can be done, and would hope to have either a commit for it or pointers for you.

**Comment by dg01d** [comment]
Okay, Paul, I think that should do it.

Script now needs a setting in configs.php `frontFormat => json|yaml`
Also added `symphony\yaml` as a dependency. 

All worked perfectly well on my test server, please let me know if you experience any issues.

**Comment by paulrobertlloyd** [comment]
Thank-you!! I have created a few subsequent issues after my initial testing. I hope these are helpful in enabling you to develop this package further.

**Comment by paulrobertlloyd** [comment]
With `yaml` selected as output format, front matter is formatted as expected.
