### ISSUE TITLE
Feature request: Allow folder locations to be customised

### ISSUE THREAD

**Issue by paulrobertlloyd** [dg01d/nanopub#6]
As noted in the code, currently files are saved to hard coded locations. Allowing these to be customised (I guess on a post-type basis) would enable this to work with different folder set ups.

**Comment by dg01d** [comment]
This is something i've wanted to have for quite some time. Will look into it again.

**Comment by skpy** [comment]
I'd like to see this, too!  Setting a base path in `configs.php` for content seems like a logical choice.

**Comment by dg01d** [comment]
This feature has now been added, thanks to @Zegnat in #17 

Closing the issue for now.
