### ISSUE TITLE
Generated file is always named Array.md

### ISSUE THREAD

**Issue by paulrobertlloyd** [dg01d/nanopub#7]
Not sure if I’ve not got something set up correctly – or perhaps because I’m not using Hugo (I’m testing using a bare site that only includes the code for nanopub) – but when posting via [Quill](https://quill.p3k.io/new), the resulting file is always called `Array.md`.

**Comment by dg01d** [comment]
I cannot replicate this on my test bare server. 

Files are called `$slug.md` in both YAML & JSON uses.

**Comment by dg01d** [comment]
This appears to be linked to #8

**Comment by paulrobertlloyd** [comment]
I can confirm that this issue does relate to #8.
