### ISSUE TITLE
YAML: slug value is saved as an array

### ISSUE THREAD

**Issue by paulrobertlloyd** [dg01d/nanopub#8]
When writing files using the YAML front matter format, the `slug` value is returned as an array, i.e.:

```yaml
slug:
    - my-nanopub-micro-note
```

As `slug` is a single value, the expected output is `slug: my-nanopub-micro-note`.

**Comment by dg01d** [comment]
I cannot replicate this on my test bare server. In each case (JSON & YAML) slug is returned as a single line, not as an array.

Relevant lines in the script are 592 &subsq:

```php
                // server allows client to set a slug
                if (!empty($props['mp-slug']['0'])) {
                    $frontmatter['slug'] = $props['mp-slug']['0'];
                    unset($props['mp-slug']);
                } elseif (!empty($frontmatter['title']['0'])) {
                    $frontmatter['slug'] = strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $frontmatter['title'])));
                } else {
                    $frontmatter['slug'] = $udate;
                }
```

**Comment by dg01d** [comment]
This should now act as expected, following commit b5f86b5.
Please test and confirm.

**Comment by paulrobertlloyd** [comment]
I’m still seeing the same issue – however, this is when I send a `slug` value. When I send `mp-slug`, everything works as expected. I’m testing using Quill, which gives you the option, and suggests that `slug` has been deprecated. So, short of supporting both values, using `mp-slug` fixes this issue.

**Comment by dg01d** [comment]
Added note to the README regarding this matter. Deprecated formats are a matter for client, not server. Accordingly, I'm marking this as closed.
