### ISSUE TITLE
Feature request: Publish to GitHub

### ISSUE THREAD

**Issue by paulrobertlloyd** [dg01d/nanopub#9]
This feature request is probably quite a complex and far reaching, but adding for consideration. This feature can be seen in other similar Micropub libraries ([webpage-micropub-to-github](https://github.com/voxpelli/webpage-micropub-to-github), [micropub-github-pages](https://github.com/lildude/micropub-github-pages)), where the resulting document is saved to a GitHub repo, rather than directly to a server.

This is particularly useful for those cases where a site is hosted with GitHub Pages, if a publisher wishes to version their files, or generate them as part of a continuous integration workflow.

**Comment by dg01d** [comment]
This is outside the scope of nanopub. Versioning of files or use in CI is a matter for a user, not for a publisher.
